### PR TITLE
Inject `XCADDY_GO_BUILD_FLAGS` through `go` operations (#102)

### PR DESCRIPTION
**Pull request by akeskimo**
Commit 47f9ded5d83ca8e701852ca7ad57cd3453e6f988 is not sufficient alone to
ensure that all go modules are installed with write bit set because 'go mod'
or 'go get' might install submodules of other modules as read-only.

If set, the environment variable appends '-modcacherw' to go mod and go get
to ensure that submodules of other modules have write access.

### CODE REVIEW

**Comment by akeskimo** [comment]
Relates to #102 which was not fully resolved, yet.

**Comment by mohammed90** [comment]
It's best if we don't make super specific flags for the various possible options. According to the [go command docs](https://pkg.go.dev/cmd/go) -- emphasis mine:
> The **build flags** are shared by the build, clean, get, install, list, run, and test commands: 

The env var introduced earlier is concerned with **build flags**. What do you think of injecting the provided `XCADDY_GO_BUILD_FLAGS` across the various commands instead of injecting the `-modcacherw` as a separate flag? Does this resolve your issue?

**Comment by akeskimo** [comment]
Yes, that will also work. I will amend the change.

**Comment by akeskimo** [comment]
@mohammed90, I think this patch version is better but it does not support build flags to all those commands that you suggested so I think I can improve this a bit. The only common interface that I could find was this

environment.go:
```go
func (env environment) newCommand(command string, args ...string) *exec.Cmd {
	cmd := exec.Command(command, args...)
	cmd.Dir = env.tempFolder
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd
}
```
so I could change this interface to append the build flags but I was not sure if you would be OK with it. What do you think?

**Comment by akeskimo** [comment]
To see more concrete example, my proposal would be like this [commit](https://github.com/caddyserver/xcaddy/commit/1dbee1d515ea3dfe1a5bd41367a8af0cd2fe5d65).

**Comment by mohammed90** [comment]
> @mohammed90, I think this patch version is better but it does not support build flags to all those commands that you suggested so I think I can improve this a bit. The only common interface that I could find was this
> 
> environment.go:
> 
> ```go
> func (env environment) newCommand(command string, args ...string) *exec.Cmd {
> 	cmd := exec.Command(command, args...)
> 	cmd.Dir = env.tempFolder
> 	cmd.Stdout = os.Stdout
> 	cmd.Stderr = os.Stderr
> 	return cmd
> }
> ```
> 
> so I could change this interface to append the build flags but I was not sure if you would be OK with it. The name of that method is very generic and it could be potentially used for running other than build-related commands. What do you think?

A method like this can guarantee it's only using `go` command.

```go
func (env environment) newGoCommand(args ...string) *exec.Cmd {
	return env.newCommand(utils.GetGo(), args...)
}

```

**Review by mohammed90 — APPROVED** [review]
Looks good! I'll merge this as-is now, but I'll follow it up with another commit. `mod` supports `modcacherw`, `modfile`, and `overlay` of the build flags, BUT not the rest. The next commit will add `XCADDY_GO_MOD_FLAGS` which will only apply to `go mod`. In your case, you will need to add `-modcacherw` to both env vars.

Thanks for the  work on the PR!

**Comment by akeskimo** [comment]
Sounds good to me. Thank you for your help, Mohammed!

**Pull request merged**
