### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by AtomBaf**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitLab, GitHub, and Bitbucket that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

### CODE REVIEW

**Comment by francislavoie** [comment]
https://github.com/features/codespaces makes this pointless. And @mholt has Go installed on his own machine, so he'll never use this.

This honestly reads like advertisement/spam.

**Comment by AtomBaf** [comment]
> https://github.com/features/codespaces makes this pointless. And @mholt has Go installed on his own machine, so he'll never use this.
> 
> This honestly reads like advertisement/spam.

Sorry that this looks like a spam, but unfortunately there are some cases where a plugin developper won't be able to install go (corporate firewall policies for instance)

This is my case, and I want to be able to remotely build. Maybe there is another option?

**Comment by francislavoie** [comment]
Yep, use the official docker image, the builder variant: https://hub.docker.com/_/caddy

**Comment by mholt** [comment]
Well, I wouldn't consider this spam, but it's also a feature no one has asked for. I think it's better for a developer to just put these files in the project themselves if they want to use gitpod, but there's no reason, motivation, or incentive for us to favor it over any other solution. It solves a problem that isn't had by most users.

**Comment by AtomBaf** [comment]
Won't work either for me. I see some wget to github inside these dockerfiles
No luck for me I guess...

**Comment by AtomBaf** [comment]
> Well, I wouldn't consider this spam, but it's also a feature no one has asked for. I think it's better for a developer to just put these files in the project themselves if they want to use gitpod, but there's no reason, motivation, or incentive for us to favor it over any other solution. It solves a problem that isn't had by most users.

I understand, I will do it on my side. Sorry for disturbance, and btw thx for very promising stuff you built here.

**Comment by mholt** [comment]
No problem, good luck with dealing with that firewall! Sorry we can't help you more.

**Pull request closed without merging**
